package com.skysam.enlacehospitales.common

object Constants {
    const val DEMO = "debug"
    const val RELEASE = "release"
    const val MEMBERS_HLC = "membersHlc"
    const val MEMBERS_HLC_DEMO = "membersDemo"
    const val MEMBERS_GVP = "membersGvp"
    const val MEMBERS_GVP_DEMO = "membersGvpDemo"
    const val EMERGENCYS = "emergencys"
    const val EMERGENCYS_DEMO = "emergencysDemo"

    const val RESULT_OK = "ok"
    const val NAME = "name"
    const val EMAIL = "email"
    const val CONGREGATION = "congregation"
    const val PHONE = "phone"
    const val ROLE = "role"
    const val IS_ACTIVE = "isActive"

    const val ROLE_ADMIN = "admin"
    const val ROLE_HLC = "hlc"
    const val ROLE_GVP = "gvp"
    const val GUARD = "guard"

    const val DATE_CALL = "dateCall"
    const val PERSON_CALL = "personCall"
    const val RELATIONSHIP_PATIENT = "relationshipPatient"
    const val INFO_PERSON_CALL = "infoPersonCall"
    const val IS_NEED_HELP = "isNeedHelp"
    const val PATIENT = "patient"
    const val GENDER = "gender"
    const val AGE = "age"
    const val COMMENTS = "comments"
    const val IS_BAPTIZED = "isBaptized"
    const val IS_REPUTATION = "isReputation"
    const val NAME_HOSPITAL = "nameHospital"
    const val ROOM = "room"
    const val NAMES_OLDERS_CONTACTED = "namesOldersContacted"
    const val PHONES_OLDERS_CONTACTED = "phonesOldersContacted"
    const val IS_CHILD = "isChild"
    const val CHILD_PATIENT = "childPatient"
    const val NAME_FATHER = "nameFather"
    const val NAME_MOTHER = "nameMother"
    const val IS_FATHER_BAPTIZED = "isFatherBaptized"
    const val IS_MOTHER_BAPTIZED = "isMotherBaptized"
    const val IS_BORN = "isBorn"
    const val BORN_PATIENT = "bornPatient"
    const val WEIGHT = "weight"
    const val WEEKS_AGE = "weeksAge"
    const val DATE_BORN = "dateBorn"
    const val BORN_APGAR = "bornApgar"
    const val FIVE_MINUTES_APGAR = "fiveMinutesApgar"
    const val ISSUE_MEDICAL = "issueMedical"
    const val ANALISYS_LAB = "analisysLab"
    const val DATE = "date"
    const val DATE_UPDATED = "dateUpdated"
    const val HEMOGLOBINA = "hemoglobina"
    const val PLAQUETAS = "plaquetas"
    const val HEMATOCRITO = "hematocrito"
    const val OTHERS = "others"
    const val DOCTORS = "doctors"
    const val SPECIALITY = "speciality"
    const val METHOD_CONTACT = "methodContact"
    const val INFORMATION = "information"
    const val TRATMENT = "tratment"
    const val IS_COMMUNICATED_WITH_DOCTORS = "isCommunicatedWithDoctors"
    const val STRATEGIES = "strategies"
    const val ARTICLES_MEDICAL = "articlesMedical"
    const val ARTICLES = "articles"
    const val IS_DOCTOR_COLABORATED = "isDoctorColaborated"
    const val IS_TALK_WITH_SECOND_DOCTOR = "isTalkWithSecondDoctor"
    const val SECOND_DOCTOR = "secondDoctor"
    const val IS_TRANSFERED = "isTransfered"
    const val TRANSFER_PATIENT = "transferPatient"
    const val IS_PLANS_CONFIRMED = "isPlansConfirmed"
    const val IS_CONTACTED_INFORMATION_HOSPITALS = "isContactedInformationHospitals"
    const val NAME_DOCTOR = "nameDoctor"
    const val PHONE_HOSPITAL = "phoneHospital"
    const val TRACING = "TRACING"
    const val IS_CONTACTED_OLDERS_LOCALS = "isContactedOldersLocals"
    const val RESULTS = "results"

    const val PREFERENCES = "preferences"
    const val NOTIFICATION = "notification"
    const val TOPIC_ALL_NOTIFICATIONS_DEMO = "allNotificationsDemo"
    const val TOPIC_ALL_NOTIFICATIONS = "allNotifications"
    const val PREFERENCES_BIOMETRIC = "biometric"
    const val PASSWORD = "password"


    const val METHOD = "method"
    const val TITLE = "title"
    const val MESSAGE = "message"
    const val TOPIC = "topic"
    const val SUCCESS = "success"
    const val SEND_NOTIFICATION_SUCCESS = 3
    const val ERROR_METHOD_NOT_EXIST = 104
}